video_folder: "data/videos"
annotation_folder: "data/annotations"
token_folder: "data/tokens"
feature_folder: "data/features"

clip_length: 2
overlapping: 0.5

prompt: "Is the baby / mannequin visible? If yes, is the baby receiving ventilation? Is the baby being stimulated? Is the baby receiving suction? Ventilation and suction can not be performed at the same time."

system_message: |
  You are assisting in a medical simulation analysis. A camera is positioned above a table. The simulation involves a mannequin representing a newborn baby, which may or may not be present on the table.

  Your tasks are as follows:

  1. Determine Presence
  - Check if the mannequin (baby) is visible and present on the table.
  - If not present or not visible, no treatment is being performed.
  - If present, continue to the next steps.

  2. Identify the Mannequin's Face
  - Locate the face of the mannequin. This is the key area for identifying some treatments.

  3. Detect Medical Treatments
  If the mannequin is present, identify whether the following treatments are being performed. These treatments can occur individually, stimulation can occur at the same time of suction or ventilation:

  - Ventilation:
    - A healthworker is holding a ventilation mask over the mannequin's face.
    - This means ventilation is being administered.

  - Suction:
    - A tube is inserted into the mannequin's mouth or nose.
    - This means suction is being performed.

  - Stimulation:
    - A healthworker is applying stimulation to the mannequin's back, buttocks (nates), or trunk.
    - Stimulation is indicated by:
      - Hands placed on one of these areas
      - Up-and-down repetitive hand movement

  Repeat: If the mannequin is not visible, no treatment is being performed.

  Respond clearly based on what is visible in the image. Use concise and structured output when possible.

num_workers: 0

momentum: null
scheduler_patience: null
step_size: null
gamma: null
eta_min: null
factor: null
mode: null
cooldown: null
min_lr: null

threshold: 0.5

train_csv: "data/clips/train/labels.csv"
validation_csv: "data/clips/validation/labels.csv"
test_csv: "data/clips/test/labels.csv"

frame_sample: "uniform"